---
title: "whybot sentence"
author: "erin"
output: html_document
---

```{r global_options, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo=F, warning=F, cache=F, message=F,
                      sanitiz=T, fig.width = 5, fig.height = 3)
```

```{r load_settings}
library(tidyr)
library(dplyr)
library(ggplot2)
library(igraph)
library(ggthemes)
library(tidyverse)
char = as.character
num = function(x) {return(as.numeric(as.character(x)))}
library('Matrix')
```

```{r}
sentences = read.delim("../../data/experiment1/sentences_to_go_with_cosine_similarities.txt", sep="~", stringsAsFactors = F, header=F)$V1
dissent_X = read.table("../../data/experiment1/dissent_cosine_similarities.txt")
skipthoughts_X = read.table("../../data/experiment1/skip-thoughts_cosine_similarities.txt")
# dissent_embeddings = read.table("../../data/experiment1/dissent_embeddings_mtx.txt.IGNORE")
```


```{r}
# X = skipthoughts_X
X = dissent_X
```
















```{r}
V = do.call(c, as.list(X))
M = matrix(V, nrow = nrow(X), dimnames = list(sentences, sentences))
```


```{r}
# # looking at highest magnitude cosine distance is basically useless
# threshold = 0.1
# ignore_sents = c("{{}}", "Above", "Nothing")
# closest_pairs_indices = which(M<threshold, arr.ind = T)
# closest_pairs = sapply(1:nrow(closest_pairs_indices), function(i) {
#   sents = sentences[closest_pairs_indices[i,]]
#   if (!(sents[1] %in% ignore_sents | sents[2] %in% ignore_sents)) {
#     return(paste(sents, collapse=" ~ "))
#   } else {
#     return("")
#   }})
# closest_pairs[closest_pairs!=""]
```


```{r}
D = as.dist(1 - M)
```


```{r}
H = hclust(D)
```

```{r}
# lowest_merges <- H$merge[1:100,] %>% 
lowest_merges <- H$merge %>%
  as_tibble() %>%
  filter(V1 < 0, V2 < 0)

interesting_sentences <- c(89, 90, 97, 158, 155, 171, 177, 186, 235, 249)

i <- 249
Row <- M[i,]
# sentences[][1:25]

sort(Row, decreasing=TRUE)[1:10]
```

```{r}
similar_sentences1 <- sentences[-lowest_merges$V1]
similar_sentences2 <- sentences[-lowest_merges$V2]
paste(similar_sentences1, " - ", similar_sentences2)
```


```{r}
get_similar <- function(index, n=20, filter_negation=T) {
  ## gets 20 most similar sentences (w/ similarity)
  ## while accounting for negation
  ## uses a crude heuristic:
  ## detects presence of negation in sentence
  ## compares only to sentences w/ same negation status

  i <- index
  Row <- M[i, ]

  if (filter_negation) {
    negation_words <- c(
      "n't",
      "\\<not",
      "\\<cannot",
      "\\<never",
      "\\<didnt",
      "\\<no",
      "\\<doesnt",
      "\\<cant",
      "\\<wont",
      "\\<shouldnt",
      "\\<couldnt"
    )
    
    neg_search <- paste0("(", paste0(negation_words, collapse = "|"), ")")
    # SPLIT sentences into two -- one set w/ negation, one w/out negations
  
    neg_sentences_ind <- grepl(neg_search, sentences)
    pos_sentences_ind <- !grepl(neg_search, sentences)
  
    if (neg_sentences_ind[i]) {
      sort(Row[neg_sentences_ind], decreasing = TRUE)[1:n]
    } else {
      sort(Row[pos_sentences_ind], decreasing = TRUE)[1:n]
    }
  } else {
    sort(Row, decreasing = TRUE)[1:n]
  }
}

```

```{r}
# 187 was a problem (e.g.)

get_similar(187, filter_negation=F)
```

  
```{r}
graph_structure = (function() {
  transforms = c("p", "n")
  frames = c("C", "R")
  n_link_types = length(transforms)*length(frames)
  
  graph_structure = data.frame(
    transform1 = c(rep(rep(transforms, c(2,2)), 1),
                   rep(rep(transforms, c(8,8)), 1)),
    frame1 = c(rep(rep(frames, c(1,1)), 2),
               rep(rep(frames, c(4,4)), 2)),
    transform2 = c(rep("", n_link_types),
                   rep(rep(transforms, c(2,2)), 4)),
    frame2 = c(rep("", n_link_types),
               rep(rep(frames, c(1,1)), 8)),
    stringsAsFactors=F) %>%
    filter(frame1==frame2 | transform1!=transform2) %>%
    mutate(var1 = paste(transform1, frame1, sep=""),
           var2 = paste(transform2, frame2, sep=""),
           variable = paste(var1, var2, sep="")) %>%
    mutate(source = ifelse(var2=="", "D", var1),
           target = variable,
           link_type = ifelse(var2=="", var1, var2)) %>%
    select(source, target, link_type)
  
  negations = graph_structure %>% 
    # make negation links
    filter(link_type %in% c("nC", "nR")) %>%
    mutate(target = paste("-", source, sep=""),
           link_type = "neg") %>%
    rbind(graph_structure %>% 
            filter(link_type %in% c("nC", "nR")) %>%
            mutate(target = source,
                   source = paste("-", source, sep=""),
                   link_type = "neg"))
  
  # If link type is nC, that means that it caused something to not happen.
  # So it becomes a positive cause of the negation.
  causes_of_negations = graph_structure %>% 
    filter(link_type=="nC") %>%
    mutate(source = paste("-", source, sep=""),
           link_type = "pC")
  
  results_of_negations = graph_structure %>% 
    filter(link_type=="nR") %>%
    mutate(source = paste("-", source, sep=""),
           link_type = "pR")
  
  graph_structure = graph_structure %>%
    filter(!(link_type %in% c("nC", "nR"))) %>%
    rbind(negations) %>% rbind(causes_of_negations) %>%
    rbind(results_of_negations) %>%
    mutate(old_target = target,
           old_source = source,
           target = ifelse(link_type=="pC", old_source, target),
           source = ifelse(link_type=="pC", old_target, source),
           link_type = ifelse(link_type=="pC", "pR", link_type)) %>%
    select(-old_target, -old_source)
  
  reverse_negations = graph_structure %>%
    filter(link_type=="neg") %>%
    mutate(old_target = target,
           old_source = source,
           source = old_target,
           target = old_source) %>%
    select(source, target, link_type)
  
  return(rbind(graph_structure, reverse_negations))
})()

abstract_g = make_graph(as.matrix(graph_structure %>%select(source, target)) %>% t %>% c, directed=T)
```


```{r}
# given a candidate merge,
# try it out and 
# check for self-negations

# read data from js experiment
raw_df = read.csv("../../data/experiment1/all_data.csv") %>%
  # filter test and unfinished workers
  filter(!(workerid %in% c(3,4,5,6))) %>%
  # cleanup responses
  mutate(response = char(response)) %>%
  mutate(negated_response = gsub("<span class='variable_word (name|he)'>\\{\\{\\}\\}</span>",
                                 "he",
                                 negated_response),
         negated_response = gsub("<span class='variable_word (him)'>\\{\\{\\}\\}</span>",
                                 "him",
                                 negated_response),
         negated_response = gsub("<span class='variable_word (his)'>\\{\\{\\}\\}</span>",
                                 "his",
                                 negated_response)) %>%
  mutate(negated_response = ifelse(variable=="D", paste("not", response), negated_response)) %>%
  select(workerid, response, variable, negated_response)

df = do.call(rbind, lapply(unique(raw_df$workerid), function(worker_to_graph) {
  # filter to a single worker's data
  w = raw_df %>%
    select(response, negated_response, variable, workerid) %>%
    filter(workerid==worker_to_graph) %>%
    filter(!is.na(response))
  # make a mapping from variables to responses
  responses = w$response
  names(responses) = w$variable
  # make a mapping from variables to negated responses
  negated_responses = w$negated_response
  names(negated_responses) = w$variable
  
  edges_df = graph_structure %>%
    # transform from abstract graph to this particular worker's responses
    select(source, target, link_type) %>%
    mutate(source_variable = char(source),
           target_variable = char(target),
           link_type = char(link_type)) %>%
    filter((target_variable %in% w$variable) & (source %in% w$variable)) %>%
    mutate(negated_source = negated_responses[source_variable],
           source = responses[source_variable],
           target = responses[target_variable]) %>%
    mutate(negated_source = ifelse(is.na(negated_source),
                                   paste("NOT(", source, ")", sep=""),
                                   negated_source)) %>%
    # make sure negations have negated_source
    mutate(source = ifelse(link_type=="neg", negated_source, source)) %>%
    select(source, target, link_type) %>%
    unique()
  
  # # make negation links in the other direction
  # edges_df = rbind(edges_df, edges_df %>%
  #                    filter(link_type=="neg") %>%
  #                    mutate(old_source = source, old_target = target) %>%
  #                    mutate(source = old_target, target = old_source) %>%
  #                    select(source, target, link_type))
  
  return(edges_df)
})) %>% unique()

g = make_graph(as.matrix(df %>%select(source, target)) %>% t %>% c, directed=T)
E(g)$label = df$link_type
```

```{r}
get_self_negations = function(g) {
  neg_g = subgraph.edges(g, E(g)[E(g)$label=="neg"], delete.vertices = F)
  return(as_adj(neg_g) %>% diag)
}
```


```{r}
adjacency_matrix = as_adj(g)
```


```{r}
a = matrix(c(0,0,1,0,
             0,0,1,0,
             0,0,0,0,
             1,0,0,0), ncol=4, byrow=T)
a %*% a
```


```{r}
mapping = 1:719
merged_graph = contract(g, mapping, vertex.attr.comb = igraph_opt("vertex.attr.comb"))
```

```{r}
# propose a merge using lowest_merges
# if self-negations, reject
# get graph distance
current_graph = g
clusters = list()
for (i in 1:500) {
  potential_merge = -lowest_merges[i,]
  clust_index1 = potential_merge[[1]]
  clust_index2 = potential_merge[[2]]
  if (clust_index1 > 0 & clust_index2 > 0) {
    s1 = sentences[potential_merge[[1]]]
    s2 = sentences[potential_merge[[2]]]
    if (s1 %in% sentences[V(current_graph)] & s2 %in% sentences[V(current_graph)]) {
      current_s1_index = which(sentences[V(current_graph)]==s1)
      current_s2_index = which(sentences[V(current_graph)]==s2)
      mapping = 1:length(V(current_graph))
      mapping[current_s2_index:length(mapping)] = mapping[current_s2_index:length(mapping)] - 1
      mapping[current_s2_index] = current_s1_index
      merged_graph = contract(current_graph, mapping, vertex.attr.comb = igraph_opt("vertex.attr.comb"))
      self_negations = get_self_negations(merged_graph)
      if (sum(self_negations)==0) {
        # if (s1 %in% names(clusters)) {
        #   clusters[[s1]] = c(clusters[[s1]], s2)
        # } else {
        #   clusters[[s1]] = c(s2)
        # }
        current_graph <<- merged_graph
      } else {
        print(V(merged_graph)[self_negations>0])
      }
    }
  }
}
  
#   if (potential_merge[[2]]>0 & potential_merge[[1]]>0) {
#     mapping = 1:length(V(current_graph))
#     s1 = sentences[potential_merge[[1]]]
#     s2 = sentences[potential_merge[[2]]]
#     if (s1 %in% sentences[V(current_graph)] & s2 %in% sentences[V(current_graph)]) {
#       mapping[which(sentences[V(current_graph)]==s2)] = which(sentences[V(current_graph)]==s1)
#       merged_graph = contract(current_graph, mapping, vertex.attr.comb = igraph_opt("vertex.attr.comb"))
#       self_negations = get_self_negations(merged_graph)
#       if (sum(self_negations)==0) {
#         if (s1 %in% names(clusters)) {
#           clusters[[s1]] = c(clusters[[s1]], s2)
#         } else {
#           clusters[[s1]] = c(s2)
#         }
#         current_graph <<- merged_graph
#       } else {
#         print(V(merged_graph)[self_negations>0])
#       }
#     }
#   } else {
#   }
# }
```

