---
title: "Whybot"
subtitle: "Diseases"
output: html_document
fontsize: 12pt 
---

```{r global_options, include=FALSE}
rm(list=ls())
library(knitr)
knitr::opts_chunk$set(
  echo=F, warning=F, #cache=T, 
  message=F, #sanitiz =T, 
  fig.width = 5, fig.height = 3)
```

```{r}
source("~/Settings/startup.R")
library(igraph)
```

```{r}
df = read.csv("../data/pilot_disease_whybot_2017_04_10_wide_form.csv")
```

Here are mturk pilot participants' comments on the experiment:

```{r}
problems_and_comments = df %>%
  filter(comments!="" | !(problems%in%c("None", "no", "No.", "No", ""))) %>%
  group_by(userid) %>%
  summarise(comments = comments,
            problems = problems) %>%
  as.data.frame %>% flatten %>%
  mutate(comments = gsub("\n", " ", comments),
         problems = gsub("\n", " ", problems))
kable(problems_and_comments)
```

```{r}
demogragphics = merge(
  df %>% select(language, enjoyment, gender, assess,
                education, hasty_subject, userid) %>%
    gather("qualitative_qn", "qualitative_response", -userid),
  df %>% select(age, fairprice, time_in_minutes, userid) %>%
    gather("numeric_qn", "numeric_response", -userid) %>%
    mutate(numeric_response = num(numeric_response))
)
ggplot(demogragphics, aes(x=qualitative_response)) +
  geom_bar() +
  facet_wrap(~qualitative_qn, scale="free") +
  ggtitle("demographics")
ggplot(demogragphics, aes(x=numeric_response)) +
  geom_histogram() +
  facet_wrap(~numeric_qn, scale="free") +
  ggtitle("demographics")
median(df$time_in_minutes)
```

What diseases did people give?

```{r, fig.width=5, fig.height=2.5}
df %>% ggplot(., aes(x=D)) +
  geom_bar() +
  ggtitle("illnesses") +
  theme(axis.text.x=element_text(angle = -90, hjust = 0)) +
  xlab("")
ggsave("pilot_illnesses.png")
```

```{r}
# df = df %>% 
#   mutate(cause = factor(
#     C,
#     levels=c("does not wash his hands",
#              "is unlucky",
#              "slept on his side",
#              "sleeps outside most days",
#              "ate too much garlic",
#              "doesn't fit in",
#              "comes from a family with a history of autism",
#              "got exposed to a friend with the flu",
#              "has genes",
#              "got bitten by a mosquito",
#              "is sick",
#              "is predisposed to have cancer",
#              "smokes",
#              "smoked"),
#     labels=c("habit",
#              "other",
#              "habit",
#              "habit",
#              "event",
#              "other",
#              "genetics",
#              "event",
#              "genetics",
#              "event",
#              "other",
#              "genetics",
#              "habit",
#              "habit")))
```

```{r, fig.width=5, fig.height=4}
df %>%
  ggplot(., aes(x=C#, fill=cause
                )) +
  geom_bar() +
  ggtitle("causes") +
  theme(axis.text.x=element_text(angle = -90, hjust = 0)) +
  xlab("") +
  scale_fill_brewer(type="qual", palette=2)
```

```{r}
df = df %>%
  mutate(treatment = factor(
    A,
    levels=c("rests",
             "got rest",
             "gets sufficient rest",
             "drinks water",
             "drinks fluids",
             "gets chemo",
             "undergoes chemotherapy",
             "fights",
             "go to the doctor"),
    labels=c("rest",
             "rest",
             "rest",
             "drinks water",
             "drinks water",
             "chemo",
             "chemo",
             "other",
             "other")))
```

```{r, fig.width=5, fig.height=3.5}
df %>% ggplot(., aes(x=A, fill=treatment
                     )) +
  geom_bar() +
  ggtitle("treatments") +
  theme(axis.text.x=element_text(angle = -90, hjust = 0)) +
  xlab("") +
  scale_fill_brewer(type="qual", palette=2)
```

```{r}
df = df %>% mutate( C=char(C), D=char(D), S0=char(S0),
                    S1=char(S1), S2=char(S2),
                    A=char(A), R=char(R))
```

```{r}
draw_edges = function(row) {
  data.frame(
    source=c(row$C,
             row$A,
             row$D, row$D, row$D,
             ".", ".", ".",
             row$R),
    target=c(row$D,
             row$D,
             row$S0, row$S1, row$S2,
             row$S0, row$S1, row$S2,
             row$A),
    strength=c(row$CD/1000,
               row$AD/1000,
               row$DS0/1000, row$DS1/1000, row$DS2/1000,
               row$bS0/1000, row$bS1/1000, row$bS2/1000,
               row$cost),
    type=c("cause",
           "prevent",
           "cause", "cause", "cause",
           "cause", "cause", "cause",
           "prevent")) %>%
    mutate(type_number = as.numeric(factor(type)))
}
draw_nodes = function(row) {
  data.frame(
    id = c(row$R,
           row$A, row$C,
           row$D, ".",
           row$S0, row$S1, row$S2
           ),
    type = c("reason",
             "cause", "cause", 
             "illness", "illness",
             "symptom", "symptom", "symptom"
             )
  ) %>%
    group_by(id) %>%
    summarise(type = type[[1]]) %>%
    mutate(type_number = as.numeric(factor(
      type, levels=c("reason", "cause", "illness", "symptom"))))
}

draw_graph = function(row) {
  edges = draw_edges(row)
  nodes = draw_nodes(row)
  g1 <- graph_from_data_frame(d=edges, vertices=nodes, directed=T) 
  E(g1)$width <- 1+E(g1)$strength*5
  
  colrs <- c("lemonchiffon", "lightgreen", 
             "lightsteelblue", "lightcoral")
  V(g1)$color <- colrs[V(g1)$type_number]
  
  lineclrs = c("#a7b7a8", "#b7a7a7")
  edge.col = lineclrs[edges$type_number]
  
  latitude = nodes$type_number - 1

  instance_number = c()
  seen = list()
  for (i in 1:nrow(nodes)) {
    instance = char(nodes$type)[i]
    if (instance %in% names(seen)) {
      instance_of_this_type_so_far = seen[[instance]] + 1
    } else {
      instance_of_this_type_so_far = 1
    }
    instance_number <- c(instance_number,
                          instance_of_this_type_so_far-1)
    seen[[instance]] <- instance_of_this_type_so_far
  }

  counts = unname(table(nodes$type)[nodes$type])
  offsets = instance_number / (counts-1)
  offsets[is.nan(offsets)] = 0
  widths = (counts - 1)*2
  starts = -(counts-1)
  longitude = starts + offsets*widths
  
  silent = png(paste("graphs/graph_", row["userid"], "_", row["D"], ".png", sep=""),
      width=400, height=500)
  
  l <- matrix(c(longitude, -latitude), ncol=2, byrow=F)
  h = plot(g1, edge.arrow.size=.5, vertex.size=15,
           edge.color = edge.col,
           vertex.frame.color="gray", vertex.label.color="black",
           vertex.label.cex=0.8, vertex.label.dist=0.8, edge.curved=0,
           layout=l
           )
  print(h)
  silent = dev.off()
}
```

```{r}
silent = draw_graph(df[1,])
silent = draw_graph(df[2,])
silent = draw_graph(df[3,])
silent = draw_graph(df[4,])
silent = draw_graph(df[5,])
silent = draw_graph(df[6,])
silent = draw_graph(df[7,])
silent = draw_graph(df[8,])
silent = draw_graph(df[9,])
```

## Aggregate with merged nodes

```{r}
agg = read.csv("../data/pilot_aggregate_disease_whybot_2017_04_10_wide_form.csv") %>%
  mutate(A = char(A), C = char(C), D = char(D), S0 = char(S0), S1 = char(S1),
         S2 = char(S2), S3 = char(S3))

edges = data.frame(
  source = c(agg$C, agg$A,  agg$D,  agg$D,  agg$D,  agg$D),
  target = c(agg$D, agg$D, agg$S0, agg$S1, agg$S2, agg$S3),
  strength = 1,
  type = rep(c("cause", "prevent", "cause", "cause", "cause", "cause"), each=nrow(agg))
) %>% mutate(type_number = as.numeric(factor(type)))

unique_nodes = unique(c(agg$C, agg$A, agg$D, agg$S0, agg$S1, agg$S2, agg$S3))
nodes = data.frame(
  id = unique_nodes
)
  lineclrs = c("#a7b7a8", "#b7a7a7")
  edge.col = lineclrs[edges$type_number]

  g1 <- graph_from_data_frame(d=edges, vertices=nodes, directed=T)
  
  silent = png(paste("graphs/graph_aggregate.png", sep=""),
               width=1000, height=1000)
  
  h = plot(g1, edge.arrow.size=.1, vertex.size=2,
           edge.color = edge.col,
           vertex.frame.color="gray", vertex.label.color="black",
           vertex.label.cex=0.8, vertex.label.dist=0.1,
           layout=layout.auto
           )
  silent = dev.off()
  
#   add_layout_ to add the layout to the graph as an attribute.
# 
# Other graph layouts: add_layout_; as_bipartite; layout.star; layout_as_tree; layout_in_circle; layout.auto, layout.davidson.harel; layout.gem; layout.graphopt; layout.grid; layout.mds; layout_components; layout_on_sphere; layout_randomly; layout_with_fr; layout_with_kk; layout_with_lgl;
```

Next, represent each disease as a vector of its possible symptoms, causes, and treatments.

```{r}
threshold = 0
dimensions = (function() {
  treatments = names(table(agg$A)[table(agg$A)>threshold])
  causes = names(table(agg$C)[table(agg$C)>threshold])
  all_symptoms = with(agg, c(S0, S1, S2, S3))
  symptoms = names(table(all_symptoms)[table(all_symptoms)>threshold])
  symptoms = symptoms[symptoms!="other"]
  return(data.frame(
    dimname = c(treatments, causes, symptoms),
    dimtype = c(rep("A", length(treatments)),
                rep("C", length(causes)),
                rep("S", length(symptoms)))
  ))
})()

diseases = unique(agg$D)
vectors = do.call(rbind, lapply(diseases, function(disease) {
  vector = (dimensions %>% mutate(count = mapply(function(dimname, dimtype) {
    if (dimtype=="S") {
      candidates = c((agg %>% filter(D==disease))$S0,
                     (agg %>% filter(D==disease))$S1,
                     (agg %>% filter(D==disease))$S2,
                     (agg %>% filter(D==disease))$S3)
    } else {
      candidates = (agg %>% filter(D==disease))[[dimtype]]
    }
    return(sum(candidates==dimname))
  }, char(dimname), char(dimtype))))$count
  return(vector/agg %>% filter(D==disease) %>% length)
}) %>% as.data.frame)
colnames(vectors) = dimensions$dimname
rownames(vectors) = diseases
# disease = diseases[1]
# (dimensions %>% mutate(count = mapply(function(dimname, dimtype) {
#   if (dimtype=="S") {
#     candidates = c((agg %>% filter(D==disease))$S0,
#                    (agg %>% filter(D==disease))$S1,
#                    (agg %>% filter(D==disease))$S2,
#                    (agg %>% filter(D==disease))$S3)
#   } else {
#     candidates = (agg %>% filter(D==disease))[[dimtype]]
#   }
#   return(sum(candidates==dimname))
# }, char(dimname), char(dimtype))))$count %>% as.numeric %>% str
```

Now that we have the diseases vectorized, we can make some plots.

dendrogram
```{r}

```

similarity matrix (euclidean distance)
```{r}
dist(vectors, method="euclidean")
```














